# Generated by Django 6.1.1 on 2026-09-28 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_specialleavetype_leaverequest_other_special_leave_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Annual', 'Annual Leave'), ('Special', 'Special Leave'), ('Mat', 'Maternity Leave'), ('Pat', 'Paternity Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(fields=('user', 'holiday_year'), name='unique_user_holiday_year'),
        ),
    ]
