# Generated by Django 5.2.8 on 2026-10-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_leaverequest_leave_type_and_more'),
        ('leave_management', '0003_alter_leaverequest_status'),
    ]

    operations = [
    ]
