# Generated by Django 5.2.8 on 2026-10-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_alter_leaverequest_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
