# Generated by Django 6.0.4 on 2026-08-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='annual_leave',
            new_name='leave_entitlement',
        ),
    ]
