# Generated by Django 6.0.4 on 2026-08-09 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_annual_leave_userprofile_leave_entitlement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='leave_entitlement',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 8, 9)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
